
export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const UNHELPFULTOKEN = 'UNHELPFULTOKEN';
export const ENTERED = 'ENTERED';
export const VARIABLESAVED = 'VARIABLESAVED';

export const INDICATORSFETCHED = 'INDICATORSFETCHED';
export const INDICATORSCHANGED = 'INDICATORSCHANGED';
export const SPLITCHANGED = 'SPLITCHANGED';
export const UPDATECOLORS = 'UPDATECOLORS'

export const ADDSELECTEDPOINT = 'ADDSELECTEDPOINT';
export const REMOVESELECTEDPOINT = 'REMOVESELECTEDPOINT';

export const WIDGETSCHANGED = 'WIDGETSCHANGED';

